---
name: flyspark

volumes:
  node_modules: {}

services:
  app:
    image: flyskypark:prod
    container_name: flyskypark-next
    restart: unless-stopped
    build:
      context: ..
      network: host
      dockerfile: containers/Dockerfile
      args:
        NODE_VER: ${NODE_IMV_TAG:-slim}
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - ${HTTP_PORT:-3000}:3000
    volumes:
      ## Cache node modules
      - ${APP_NODE_MODULES:-node_modules}:/app/node_modules
